coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 70%

ignore:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/main.ts"
  - "**/*.module.ts"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/coverage/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
