coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/coverage/**"

flags:
  api-gateway:
    paths:
      - api-gateway/
  inventario-service:
    paths:
      - inventario-service/
  auth-service:
    paths:
      - auth-service/

comment:
  layout: "reach, diff, flags, files"
  behavior: default
